# Generated by Django 2.1.5 on 2019-01-22 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='lession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video', models.URLField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('Topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='api.topic')),
            ],
        ),
    ]
