# Generated by Django 2.1.5 on 2019-01-22 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_lession'),
    ]

    operations = [
        migrations.CreateModel(
            name='discus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('lessions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_subject', to='api.lession')),
            ],
        ),
    ]
